### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by mcgotts** [Stadicus/RaspiBolt#346]
Hi there - I set up my raspibolt just a little over a week ago as per this guide.  Since then, it appears my /dev/root directly has ballooned up to ~30G and is now full.  

Upon investigation, it appears as though these log files are the culprits:
- daemon.log at 13G
- syslog.l at 3.8G
- syslog at 3.8G
- daemon.log.1 at 3.4G

Are these log files supposed to be so big?  If so - is there an easy way to move them onto my /mnt directory without affecting the operation of my LND node?

**Comment by badokun** [comment]
Can't answer your question directly as it relates to moving it to your /mnt directory, but if you want insights into what's going on on your Raspberry I've put together a Monitoring guide under the Bonus section. The pull request is still open, but in the mean time you can look at https://github.com/badokun/guides/blob/master/raspibolt/raspibolt_71_monitoring.md. If you scroll down to the bottom you can get an idea of the graphs you'll get. Disk usage is also in there

**Comment by Stadicus** [comment]
No, these logs are not supposed to be that big. Usually, they are rotaded, compressed and deleted after some time. It seems that something creates a lot of noise. Can you share some content of the logs on pastebin.com?

**Comment by kadlma** [comment]
> Hi there - I set up my raspibolt just a little over a week ago as per this guide. Since then, it appears my /dev/root directly has ballooned up to ~30G and is now full.
> 
> Upon investigation, it appears as though these log files are the culprits:
> 
> * daemon.log at 13G
> * syslog.l at 3.8G
> * syslog at 3.8G
> * daemon.log.1 at 3.4G
> 
> Are these log files supposed to be so big? If so - is there an easy way to move them onto my /mnt directory without affecting the operation of my LND node?

I do have exactly the same problem as you do, after reboot the node is full of "No space left on device" errors.

`Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G   30G     0 100% /
devtmpfs        460M     0  460M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M  6.3M  458M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1   44M   23M   22M  51% /boot
tmpfs            93M     0   93M   0% /run/user/1000
tmpfs            93M     0   93M   0% /run/user/1001`

**Comment by Stadicus** [comment]
Can you check the content of the biggest logfiles and post some of your finding (repeated error messages, etc) here?

**Comment by faket0shi** [comment]
I've had the same problem for a couple of days now. I copy a fragment of the syslog file because daemon.log is too big to open.

Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.940 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.940 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.943 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612680864475119617, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.940 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.942 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.944 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605205284848795648, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.941 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605208583406354432, mflag$
Feb 12 06:27:07 FakeToshi lnd[733]: 2019-02-12 06:27:07.944 [DBG] PEER: Sending ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=615324090335232001, mflag$

admin@FakeToshi:/var/log $ ls -la -Ss
1721800 -rw-r-----  1 root adm  1763118213 Feb 12 08:13 daemon.log
1680160 -rw-r-----  1 root adm  1720476883 Feb 12 06:25 syslog.1
  41716 -rw-r-----  1 root adm    42710447 Feb 12 08:13 syslog
  29720 -rw-r-----  1 root adm    30425204 Feb 12 08:13 auth.log
    592 -rw-r-----  1 root adm      598909 Feb 10 05:47 kern.log.1
    576 -rw-r-----  1 root adm      584924 Feb 10 06:26 messages.1
    320 -rw-r-----  1 root adm      320388 Feb 12 07:14 kern.log
    308 -rw-r-----  1 root adm      311152 Feb 12 07:14 messages
      8 -rw-rw-r--  1 root utmp     292876 Feb 12 07:50 lastlog
    244 -rw-r-----  1 root adm      245623 Feb 10 05:47 ufw.log.1
    108 -rw-r-----  1 root adm      106236 Feb 12 07:14 ufw.log
    104 -rw-r--r--  1 root root     100526 Feb  2 11:23 dpkg.log
     88 -rw-rw-r--  1 root utmp      85632 Feb 12 07:50 wtmp
      8 -rw-r--r--  1 root root      24072 Jan 18 13:39 faillog
     24 -rw-r-----  1 root adm       17923 Feb  7 14:49 fail2ban.log.1
     16 -rw-r-----  1 root adm       15443 Feb  5 07:27 debug.1
     16 -rw-r-----  1 root adm       14387 Feb 11 17:45 fail2ban.log
     12 -rw-r-----  1 root adm        9502 Feb 11 17:45 debug
     12 -rw-r--r--  1 root root       9468 Jan 18 13:38 alternatives.log
      8 -rw-r--r--  1 root root       7340 Jan 18 13:48 Xorg.0.log
      8 -rw-r-----  1 root adm        5836 Feb  5 07:27 user.log.1
      8 -rw-r--r--  1 root root       5377 Feb 11 17:45 boot.log
      8 -rw-r-----  1 root adm        4708 Feb 11 17:45 user.log
      4 drwxr-xr-x  5 root root       4096 Feb 12 08:12 .
      4 drwxr-xr-x 11 root root       4096 Jan 18 13:48 ..
      4 drwxr-xr-x  2 root root       4096 Feb  2 11:23 apt
      4 drwx--x--x  2 root root       4096 Nov 13 14:11 lightdm
      4 drwxr-x---  2 root adm        4096 Aug 13 21:49 samba
      4 -rw-------  1 root utmp       1536 Jan 21 15:26 btmp
      0 -rw-r--r--  1 root root          0 Nov 13 14:10 bootstrap.log
      0 -rw-r--r--  1 root root          0 Nov 13 14:10 fontconfig.log

yesterday I deleted the logs, so the size of the logs is less than 12 hours.

**Comment by Stadicus** [comment]
Not sure why this FakeToshi node causes so many channel updates. But these are Debugging messages. Are you sure you have `debuglevel=info` set in the `lnd.conf`?

**Comment by faket0shi** [comment]
You're right, I was in debuglevel=debug but I do not know how it has changed. I have left it in =info and it seems that everything is correct, thank you.

**Comment by robclark56** [comment]
More on this ... I also ran out of space on /

I found my logs were full of gazillions of messages like this:
```
Feb 19 08:17:34 RaspiBolt lnd[19836]: 2019-02-19 08:17:34.353 [ERR] DISC: unable to validate channel update announcement for short_chan_id=(lnwire.ShortChannelID) 557818:1437:1
Feb 19 08:17:34 RaspiBolt lnd[19836]: : invalid signature for channel update (*lnwire.ChannelUpdate)(0x226a41b0)({
Feb 19 08:17:34 RaspiBolt lnd[19836]:  Signature: (lnwire.Sig) (len=64 cap=64) {
Feb 19 08:17:34 RaspiBolt lnd[19836]:   00000000  68 0b 03 8e 2c 65 45 05  82 9d f4 2b 28 54 76 ef  |h...,eE....+(Tv.|
Feb 19 08:17:34 RaspiBolt lnd[19836]:   00000010  34 32 25 e0 4d a5 f3 2c  0a 3e 0e 07 cc 91 0d 46  |42%.M..,.>.....F|
Feb 19 08:17:34 RaspiBolt lnd[19836]:   00000020  28 e8 1c bd 93 0f 03 e3  1e d9 18 52 70 ae 74 de  |(..........Rp.t.|
Feb 19 08:17:34 RaspiBolt lnd[19836]:   00000030  ac 40 84 85 b5 07 46 a9  64 a5 c4 a8 be 55 6e 9c  |.@....F.d....Un.|
Feb 19 08:17:34 RaspiBolt lnd[19836]:  },
Feb 19 08:17:34 RaspiBolt lnd[19836]:  ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  ShortChannelID: (lnwire.ShortChannelID) 557818:1437:1,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  Timestamp: (uint32) 1550535425,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  Flags: (lnwire.ChanUpdateFlag) 259,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  TimeLockDelta: (uint16) 144,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  BaseFee: (uint32) 1000,
Feb 19 08:17:34 RaspiBolt lnd[19836]:  FeeRate: (uint32) 1
Feb 19 08:17:34 RaspiBolt lnd[19836]: })
```
My lnd.conf has
```
[Application Options]
debuglevel=info
debughtlc=false
```

**Comment by Stadicus** [comment]
Seems that the automatic log rotation is not always sufficient. Have a look at this here, I think this topic needs to be included in the guide. Any help appreciated! :-)

https://www.networkworld.com/article/3218728/linux/how-log-rotation-works-with-logrotate.html

**Comment by robclark56** [comment]
not elegant...but here is how I quickly worked around this

admin ~  ฿  ls /etc/cron.hourly/clean_logs
-rwxr-xr-x 1 root root 58 Feb 18 14:18 /etc/cron.hourly/clean_logs
admin ~  ฿  cat /etc/cron.hourly/clean_logs
#!/bin/bash
rm /var/log/syslog.*
rm /var/log/daemon.log.*
admin ~  ฿

**Comment by Stadicus** [comment]
Ok, that's blunt force... :-)

**Comment by robclark56** [comment]
:-)  Yes .... had to find a quick fix as running out of space on "/" is not cool.

But .... this weekend I migrated from V0.4.2 to V0.5.2. Guess what? All those messages filling up my log files have stopped!

My GUESS: V0.4.2 was not happy with some messages coming out of the newer LND versions.

My other Guess?: Prior to the migration, I closed a few channels (as that was the advice from others who had seen funds lost if upgrading). Maybe one of those channels was responsible.

Anyway - there is a datapoint for you.
