### ISSUE TITLE
Automatic Dropbox SCB backup fails

### ISSUE THREAD

**Issue by Yasoj** [Stadicus/RaspiBolt#712]
I followed the guide. However, the Dropbox menu is a bit different now, so I created a 'short-lived access token' which seems to be the recommended option (rather than one with no expiration).

When I do the test at the end, the file is not copied in my Dropbox folder.
The output of `sudo journalctl -fu backup-channels` is:

```
Uploading signature: 'channel.backup.md5'...
parse error: Invalid numeric literal at line 1, column 6
Unknown error when uploading...
/usr/local/bin/lnd-channel-backup.sh: line 151: inotifywait: command not found
Copying backup file...
Uploading backup file: 'channel.backup'...
parse error: Invalid numeric literal at line 1, column 6
Unknown error when uploading...
```

**Comment by IdrisMiles** [comment]
I ran into this issue to, the fix is:
- in the dropbox app settings, go to the permissions tab
- enable `files.content.write` and `files.metadata.write` (I also enabled `files.content.read` for good measure but don't think that's required)
- save, then refresh the page and hit generate auth token again and use that one

![dropbox_upload](https://user-images.githubusercontent.com/8471804/113332687-6c937280-9319-11eb-8ec0-c03338abbfb7.png)

**Comment by Yasoj** [comment]
Perfect, it now works for me, thank you very much!
